# Generated by Django 5.2 on 2025-05-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0002_veiculo_foto_alter_veiculo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='veiculo/fotos', verbose_name='Foto'),
        ),
    ]
