# Generated by Django 5.2 on 2025-05-21 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0003_alter_veiculo_foto (2)'),
        ('veiculo', '0003_alter_veiculo_foto'),
    ]

    operations = [
    ]
